CnNazaninProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('services/', include('services.urls', namespace='services')),
    path('other/', include('other.urls', namespace='other')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail_cart/', views.DetailCart.as_view(), name='detail_cart'),
    path('add_object/<int:product_id>/', views.AddCartObject.as_view(), name='add_object'),
    path('remove_object/<int:product_id>/', views.RemoveObject.as_view(), name='remove_object'),
#    path('apply_coupon/', views.ApplyCoupon.as_view(), name='apply_coupon'),
    path('checkout_cart/', views.CheckoutCart.as_view(), name='checkout_cart'),

]

other/urls.py
from . import views
from django.urls import path


app_name = 'other'

urlpatterns = [

    # --------------------------------------- contact us --------------------------------------------- #
    path('contact_us/', views.ContactUs.as_view(), name='contact_us'),

    # ------------------------------------ news ------------------------------------------------------- #
    path('sort_news_by_date/', views.SortNewsByDate.as_view(), name='sort_news_by_date'),
    path('sort_news_by_must_visited/', views.SortNewsByMustVisit.as_view(), name='sort_news_by_must_visited'),
    path('search_news/', views.SearchNews.as_view(), name='search_news'),
    path('add_reply_news/<int:news_id>/<int:comment_id>/', views.add_reply_news, name='add_reply_news'),
    path('news/', views.AllNews.as_view(), name='all_news'),
    path('detail_news/<slug:slug>/', views.DetailNews.as_view(), name='detail_news'),
    # ------------------------------------ product filter ---------------------------------------------- #
    path('search/', views.SearchProduct.as_view(), name='search'),
    path('search_result/', views.SearchResult.as_view(), name='search_result'),
    path('sort_by_lowest_price/', views.SortByLowestPrice.as_view(), name='sort_by_lowest_price'),
    path('sort_by_date/', views.SortByDate.as_view(), name='sort_by_date'),
    path('free_products/', views.FreeProduct.as_view(), name='free-products'),
    path('sort_by_must_visited/', views.SortProductByMustVisit.as_view(), name='sort_by_must_visited'),

]

services/urls.py
from . import views
from django.urls import path


app_name = 'services'

urlpatterns = [
    path('add_reply/<int:product_id>/<int:comment_id>/', views.add_reply_product, name='add_reply'),
    # ---------------------------------- services ----------------------------------- #
    path('web_design/', views.WebDesign.as_view(), name='web_design'),
    path('graphic_design/', views.GraphicDesign.as_view(), name='graphic_design'),
    path('research_and_type/', views.ResearchAndTyping.as_view(), name='research_and_type'),
    path('online_registration/', views.OnlineRegistration.as_view(), name='online_registration'),
    path('translation/', views.Translation.as_view(), name='translation'),


    # __________________________________ product  ____________________________________ #
    path('products/', views.AllProduct.as_view(), name='all_product'),
    path('products/<slug:slug>/', views.AllProduct.as_view(), name='category_filter'),
    path('detail_product/<slug:slug>/', views.DetailProduct.as_view(), name='detail_product'),

]

other/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify
from taggit.managers import TaggableManager


class News(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True, unique=True)
    slug = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='news/images/', null=True, blank=True)
    body = RichTextUploadingField(null=True, blank=True)
    most_visited = models.SmallIntegerField(null=True, blank=True, default=0)
    tags = TaggableManager()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class NewsComment(models.Model):
    name = models.CharField(max_length=65)
    news = models.ForeignKey(News, on_delete=models.CASCADE, related_name='pcomment')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='rcomment')
    is_reply = models.BooleanField(default=False)
    comment = models.TextField(max_length=400,)
    created = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager()

    def __str__(self):
        return f'{self.name} - {self.comment[:30]}'

    class Meta:
        ordering = ('-created',)


class Contact(models.Model):
    name = models.CharField(max_length=10)
    email = models.EmailField(max_length=150)
    topic = models.CharField(max_length=150)
    body = models.TextField()

    def __str__(self):
        return f'{self.email} - {self. topic}'

other/forms.py
from django import forms
from .models import Contact


class SearchProductForm(forms.Form):
    search = forms.CharField(required=False,  max_length=100)


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'

other/views.py
from django.shortcuts import get_object_or_404
from .models import News, NewsComment, Contact
from services.models import Product
from django.db.models import Q
from services.forms import AddCommentForm, AddReplyForm
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from .forms import SearchProductForm, ContactForm


# ____________________________________________ NEWS ___________________________________________ #


class AllNews(View):
    def get(self, request):
        news = News.objects.order_by('-created')
        form = SearchProductForm(request.GET)
        if 'search' in request.GET:
            if form.is_valid():
                cd = form.cleaned_data
                news = news.filter(title__icontains=cd['search'])
                return render(request, 'other/search-result.html', {'form': form, 'news': news})
            messages.error(request, 'لطفا اطلاعات معتبر وارد کنید', 'error')
            return render(request, 'other/all-news.html', {'form': form, 'news': news})
        return render(request, 'other/all-news.html', {'form': form, 'news': news})


class DetailNews(View):
    template_name = 'other/detail-news.html'
    form_class = AddCommentForm

    def get(self, request, slug):
        news = get_object_or_404(News, slug=slug)
        news.most_visited += 1
        news.save()
        comments = NewsComment.objects.filter(news=news, is_reply=False)
        reply_form = AddReplyForm()
        similar_news = news.tags.similar_objects()
        return render(request, self.template_name, {'news': news, 'similar_news': similar_news, 'comments': comments,
                                                    'form': self.form_class, 'reply': reply_form})

    def post(self,  request, slug):
        news = get_object_or_404(News, slug=slug)
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_comment = NewsComment.objects.create(comment=cd['comment'], news=news, name=cd['name'])
            new_comment.save()
            messages.success(request, 'نظر شما با موفقیت اضافه شد')
            return redirect('other:detail_news', news.slug)
        messages.success(request, 'لطفادوباره امتحان کنید')
        return redirect('other:detail_news', news.slug)


def add_reply_news(request, news_id, comment_id):
    news = get_object_or_404(News, id=news_id)
    comment = get_object_or_404(NewsComment, id=comment_id)
    if request.method == 'POST':
        form = AddReplyForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            reply = NewsComment.objects.create(name=cd['name'], news=news, reply=comment, comment=cd['comment'],
                                               is_reply=True).save()
            return redirect('other:detail_news', news.slug)
    return redirect('other:detail_news', news.slug)
# ____________________________________________ SORT ___________________________________________ #


class SortByDate(View):
    def get(self, request):
        products = Product.objects.order_by('-updated')
        form = SearchProductForm(request.GET)
        if 'search' in request.GET:
            if form.is_valid():
                cd = form.cleaned_data
                products = products.filter(Q(title__icontains=cd['search']) | Q(short_description=cd['search']))
                return render(request, 'other/search-result.html', {'form': form, 'products': products})
            messages.error(request, 'please inter valid data', 'error')
            return render(request, 'services/all-product.html', {'form': form})
        context = {'products': products, 'form': form}
        return render(request, 'services/all-product.html', context)


class SortProductByMustVisit(View):      # پر بازدید ترین
    def get(self, request):
        products = Product.objects.order_by('-most_visited')
        form = SearchProductForm(request.GET)
        if 'search' in request.GET:
            if form.is_valid():
                cd = form.cleaned_data
                products = products.filter(Q(title__icontains=cd['search']) | Q(short_description=cd['search']))
                return render(request, 'other/search-result.html', {'form': form, 'products': products})
            messages.error(request, 'please inter valid data', 'error')
            return render(request, 'services/all-product.html', {'form': form})
        context = {'products': products, 'form': form}
        return render(request, 'services/all-product.html', context)


class SortByLowestPrice(View):
    def get(self, request):
        products = Product.objects.order_by('price')
        form = SearchProductForm(request.GET)
        if 'search' in request.GET:
            if form.is_valid():
                cd = form.cleaned_data
                products = products.filter(Q(title__icontains=cd['search']) | Q(short_description=cd['search']))
                return render(request, 'other/search-result.html', {'form': form, 'products': products})
            messages.error(request, 'please inter valid data', 'error')
            return render(request, 'services/all-product.html', {'form': form})
        context = {'products': products, 'form': form}
        return render(request, 'services/all-product.html', context)

# ____________________________________________ SEARCH ___________________________________________ #


class SearchProduct(View):
    def get(self, request):
        products = Product.objects.all()
        form = SearchProductForm
        if 'search' in request.GET:
            if form.is_valid():
                cd = form.cleaned_data
                products = products.filter(Q(title__icontains=cd['search']) | Q(short_description__icontains=cd['search']))
                return render(request, 'other/search-result.html', {'form': form, 'products': products})
            messages.error(request, 'please inter valid data', 'error')
            return render(request, 'services/all-product.html', {'form': form})
        return render(request, 'services/all-product.html', {'form': form})


class SearchResult(View):
    def get(self, request):
        return render(request, 'other/search-result.html')

# ____________________________________________ Other ___________________________________________ #


class FreeProduct(View):
    def get(self, request):
        products = Product.objects.filter(price=0)
        form = SearchProductForm(request.GET)
        if 'search' in request.GET:
            if form.is_valid():
                cd = form.cleaned_data
                products = products.filter(Q(title__icontains=cd['search']) | Q(short_description=cd['search']))
                return render(request, 'other/search-result.html', {'form': form, 'products': products})
            messages.error(request, 'please inter valid data', 'error')
            return render(request, 'services/all-product.html', {'form': form})
        context = {'products': products, 'form': form}
        return render(request, 'services/all-product.html', context)


# ____________________________________________ CONTACT ___________________________________________ #


class ContactUs(View):
    template_name = 'other/cantact-us.html'
    form_class = ContactForm

    def get(self, request):
        contact = Contact.objects.last()
        return render(request, self.template_name, {'contact': contact, 'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'پیام شما با موفقیت ارسال به زودی پاسخ شماراخواهیم داد', 'success')
            return redirect('other:contact_us')
        messages.error(request, 'لطفا اطلاعات معتبر وارد کنید', 'error')
        return redirect('other:contact_us')


# ____________________________________________ SORT BY ___________________________________________ #


class SortNewsByDate(View):
    def get(self, request):
        news = News.objects.order_by('-updated')
        form = SearchProductForm(request.GET)
        if 'search' in request.GET:
            if form.is_valid():
                cd = form.cleaned_data
                news = news.filter(title__icontains=cd['search'])
                return render(request, 'other/search-result.html', {'form': form, 'news': news})
            messages.error(request, 'لطفا اطلاعات معتبر وارد کنید', 'error')
            return render(request, 'other/all-news.html', {'form': form})
        context = {'news': news, 'form': form}
        return render(request, 'other/all-news.html', context)


class SortNewsByMustVisit(View):      # پر بازدید ترین
    def get(self, request):
        news = News.objects.order_by('-most_visited')
        form = SearchProductForm(request.GET)
        if 'search' in request.GET:
            if form.is_valid():
                cd = form.cleaned_data
                news = news.filter(title__icontains=cd['search'])
                return render(request, 'other/search-result.html', {'form': form, 'news': news})
            messages.error(request, 'لطفا اطلاعات معتبروارد کنید', 'error')
            return render(request, 'other/all-news.html', {'form': form})
        context = {'news': news, 'form': form}
        return render(request, 'other/all-news.html', context)


class SearchNews(View):
    def get(self, request):
        news = News.objects.all()
        form = SearchProductForm
        if 'search' in request.GET:
            if form.is_valid():
                cd = form.cleaned_data
                news = news.filter(title__icontains=cd['search'])
                return render(request, 'other/search-result.html', {'form': form, 'news': news})
            messages.error(request, 'لطفا اطلاعات معتبر وارد کنید', 'error')
            return render(request, 'other/all-news.html', {'form': form, 'news': news})

other/templates/other/all-news.html
{% extends 'base.html' %}
{% block tit %}اخبار{% endblock tit %}
{% block content %}

    <div class="navbar navbar-dark row" style="margin-top: 35px; margin-right: 3%">
        <form action="">
            {{ form }}
            <input type="submit" value="جستوجو">
        </form>
    </div>

    <div class="row" style="margin-left: 5%; margin-right: 5%">
        <div id="filter pro" class="col-lg-12 col-md-12 col-sm-12 col-xl-12">
            <div  class="dropdown-toggle btn btn-block btn-dark "
                  style="margin-top: 1%;" id="filter" role="button" data-toggle="dropdown">
               فیلتر کردن محصولات
            </div>
                <div class="dropdown-menu text-right" aria-labelledby="filter">
                    <a href="{% url 'other:all_news' %}" class="dropdown-item">همه خبرها</a>
                    <a href="{% url 'other:sort_news_by_must_visited' %}" class="dropdown-item">پربازدید ترین ها</a>
                    <a href="{% url 'other:sort_news_by_date' %}" class="dropdown-item">جدیدترین ها </a>
                </div>
        </div>
    </div>

    <div class="row" style="margin-top: 60px; margin-right: 2px; margin-left: 2px;">
        {% for n in news %}
            <div class="col-sm-12 col-lg-2 col-md-2 col-xl-2" style="margin: 2px">
                <div class="thumbnail">
                    {% if n.image %}
                        <img src="{{ n.image.url }}" alt="{{ n.slug }}" height="150" width="100%">
                    {% endif %}
                    <div class="caption">
                        <h3>{{ n.title }}</h3>
                        <p> <a href="{% url 'other:detail_news' n.slug %}" class="btn btn-primary btn-block" role="button">دیدن جزییات</a></p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

other/templates/other/cantact-us.html
{% extends 'base.html' %}
{% block tit %}تماس با ما{% endblock tit %}
{% block content %}
    <section class="ftco-section">
		<div class="container">


			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5 col-xl-12">
					<h2 class="heading-section">Contact Form</h2>
				</div>
			</div>

			<div class="row justify-content-center text-right">
                <div class="col-md-12">
                    <div class="wrapper">
                        <div class="row no-gutters">
                            <div class="col-lg-8 col-md-7 order-md-last d-flex align-items-stretch">
                                    <div class="contact-wrap w-100 p-md-5 p-4">
                                        <h3 class="mb-4">با ما در تماس باشید</h3>
                                        <div id="form-message-warning" class="mb-4"></div>
                                <div id="form-message-success" class="mb-4">
                                دوست عزیز برای برقرای ارتباط با ما و ارسال نظرات و پیشنهادات خود میتواند از فرم زیر استفاده کنید.
                                </div>
                                        <form method="post" id="contactForm" name="contactForm" class="contactForm" novalidate action="">
                                            {% csrf_token %}
                                            {{ form.non_field_errors }}
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        {{ form.name.errors }}
                                                        <label class="label" for="name">نام</label>
                                                        <input type="text" class="form-control" name="name" id="name" placeholder="نام">
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        {{ form.email.errors }}
                                                        <label class="label" for="email">ادرس ایمیل</label>
                                                        <input type="email" class="form-control" name="email" id="email" placeholder="ایمیل">
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        {{ form.topic.errors }}
                                                        <label class="label" for="name">موضوع</label>
                                                        <input type="text" class="form-control" name="topic" id="topic" placeholder="موضوع">
                                                    </div>
                                                </div>

                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        {{ form.body.errors }}
                                                        <label class="label" for="#">پیام</label>
                                                        <textarea name="body" class="form-control" id="body" cols="30" rows="4" placeholder="پیام"></textarea>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <input type="submit" value="ارسال پیام" class="btn btn-primary">
                                                        <div class="submitting"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            <div class="col-lg-4 col-md-5 d-flex align-items-stretch" style="margin-bottom: 2%">
                                <div class="info-wrap bg-primary w-100 p-md-5 p-4">
                                    <h3 style="color: white;">برای  ارتباط بیشتر</h3>
                                    <p class="mb-4">We're open for any suggestion or just to have a chat</p>
                                    <div class="dbox w-100 d-flex align-items-start">
                                        <div class="icon d-flex align-items-center justify-content-center">
                                            <span class="fa fa-map-marker"></span>
                                        </div>
                                        <div class="text pl-3">
                                            <p>گجساران سمت راست فلکه فرودگاه </p>
                                        </div>
                                    </div>
                                    <div class="text pl-3">
                                        <p><span class="fab fa-whatsapp"></span>
                                            <a  style="color: white;" href='https://api.whatsapp.com/send?phone=989931258311'>
                                        واتساپ</a></p>
                                    </div>

                                    <div class="text pl-3">
                                        <p><span class="fab fa-whatsapp-square"></span>
                                            <a  style="color: white;" href='https://chat.whatsapp.com/I8qDyurFyz4IhLur3qer48'>
                                        گروه واتس اپ</a></p>
                                    </div>

                                    <div class="text pl-3">
                                        <p><span class="fab ti-email"></span>
                                            <a  style="color: white;" href='mailto:internetcafenazanin@gmail.com'>
                                        ایمیل</a></p>
                                    </div>
                                    <div class="text pl-3">
                                        <p><span class="fa fa-sms"></span>
                                            <a  style="color: white;" href='sms:09931258311'>
                                        پیام</a></p>
                                    </div>

                                    <div class="text pl-3">
                                        <p><span class="fab fa-instagram"></span>
                                            <a  style="color: white;" href='https://instagram.com/internet_cafe.nazanin'>
                                        اینستاگرام</a></p>
                                    </div>

                                    <div class="text pl-3">
                                        <p><span class="fa pe-7s-call"></span>
                                            <a  style="color: white;" href='tel:09931258311'>
                                         تماس</a></p>
                                    </div>

                                    <div class="text pl-3">
                                        <p><span class=""></span>
                                            <a  style="color: white;" href='http://splus.ir/internetcafenazanin'>
                                         سروش</a></p>
                                    </div>

                                    <div class="text pl-3">
                                        <p><span class=""></span>
                                            <a  style="color: white;" href='https://eitaa.com/internetcafenazanin'>
                                         ایتا</a></p>
                                    </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
	</section>

{% endblock content %}

other/templates/other/detail-news.html
{% extends 'base.html' %}
{% block tit %}اخبار{% endblock tit %}
{% block content %}
    <section class="banner-area py-5">
        <div class="container">
            <div class="row  align-items-center">
                <div class="col-md-12 col-lg-12 col-xl-12 text-right text-lg-right">
                    <div class="main-banner">

                        <p class="display-4 mb-4 font-weight-normal">
                            {{ news.title }}
                        </p>
                        <div>
                            {{ news.body|safe }}
                            <small>{{ news.updated }}</small>
                        </div>

                        <div class="row" style="margin-top: 50px; margin-right: 2%; margin-left: 12%;">
                            {% for similar in similar_news  %}
                                {% if similar.title != news.title %}
                                    <div class="col-3" style="margin-right: 2%">
                                        <div class="thumbnail">
                                            <img src="{{ similar.image.url }}" alt="{{ similar.title }}" height="150" width="100%">
                                            <div class="caption">
                                                <h3>{{ similar.title }}</h3>

                                                <p><a href="{% url 'other:detail_news' similar.slug %}"
                                                      class="btn btn-primary btn-block" role="button">دیدن جزییات</a></p>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            {% empty %}
                                خبری مشابه این خبر وجود ندارد
                            {% endfor %}
                        </div>
                      <hr>
                        <form action="" method="post" class="col-6">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="Send" class="btn btn-primary">
                        </form>
                        {% for comment in comments %}
                        <div>
                            <p class="card-header">{{ comment.name }}</p>
                            <p class="card-body">{{ comment.comment }}
                                <div class="card-body">
                                    <form action="{% url 'other:add_reply_news' news.id comment.id %}" method="post">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <input type="submit" value="Send">
                                    </form>
                                </div>

                                {% for reply in comment.rcomment.all %}
                                    <p class="bg-primary text-white p-3 m-5">{{ reply.name }} <br/> {{ reply.comment }}</p>
                                {% endfor %}
                            </p>
                        </div>
                    {% empty %}
                        <p>نظری وجود ندارد</p>
                    {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

other/templates/other/search-result.html
{% extends 'base.html' %}
{% block content %}
    <section class="page-section cta">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-inner bg-faded text-center rounded">
                        <h2 class="section-heading mb-5">
                            <span class="section-heading-lower">نتیجه جستوجو</span>
                        </h2>
                    {% if products %}
                        <p class="address mb-5">
                            {% for product in products %}
                                <a href="{% url 'services:detail_product' product.id %}">
                                    <img src="{{ product.image.url }}" width="150" height="150">
                                    <center>{{ product.title }}</center>
                                    <center>{{ product.get_short_description }}</center>
                                </a>
                                <hr>
                            {% empty %}
                                <h3><span class="section-heading-lower">
                                    محصول مورد نظر پیدا نشد
                                </span></h3>
                            {% endfor %}
                        </p>
                    {% endif %}

                    {% if news %}
                        <p class="address mb-5">
                            {% for n in news %}
                                <a href="{% url 'other:detail_news' n.slug %}">
                                    <img src="{{ n.image.url }}" width="150" height="150">
                                    <center>{{ n.title }}</center>
                                </a>
                                <hr>
                            {% empty %}
                                <div style="margin-top: 60px">
                                <h3>
                                    محصولی پیدا نشد
                                </h3>
                                </div>

                            {% endfor %}
                        </p>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}