CnNazaninProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('services/', include('services.urls', namespace='services')),
    path('other/', include('other.urls', namespace='other')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail_cart/', views.DetailCart.as_view(), name='detail_cart'),
    path('add_object/<int:product_id>/', views.AddCartObject.as_view(), name='add_object'),
    path('remove_object/<int:product_id>/', views.RemoveObject.as_view(), name='remove_object'),
#    path('apply_coupon/', views.ApplyCoupon.as_view(), name='apply_coupon'),
    path('checkout_cart/', views.CheckoutCart.as_view(), name='checkout_cart'),

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.CreateOrder.as_view(), name='create_order'),
   # path('detail_order/', views.DetailOrder.as_view(), name='detail_order'),
    path('history/', views.History.as_view(), name='history'),
]

cart/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    active_date_start = models.DateTimeField(null=True, blank=True)
    active_date_end = models.DateTimeField(null=True, blank=True)
    active = models.BooleanField(default=False)
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])

    def __str__(self):
        return f'{self.code} . {self.active} '

cart/forms.py
from django import forms


class CouponForm(forms.Form):
    code = forms.CharField(max_length=30)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View


from services.models import Product
from .cart_sessions import Cart
from .models import Coupon
from .forms import CouponForm


class ApplyCoupon(LoginRequiredMixin, View):
    def post(self, request):
        cart = Cart(request)
        if cart:
            form = CouponForm(request.POST)
            if form.is_valid():
                coupon_code = form.cleaned_data['code']
                try:
                    coupon = get_object_or_404(Coupon, code=coupon_code)
                    if coupon.active_date_start > timezone.now():
                        coupon.active = False
                        messages.error(request, f'This Coupon Has Not Been Activated yet. Please wait Until '
                                                f'{coupon.active_date_start}', 'error')
                    elif timezone.now() > coupon.active_date_end:
                        coupon.active = False
                        messages.error(request, 'The Deadline For Using This Coupon has passed', 'error')
                    else:
                        if coupon.active:
                            discount = cart.all_total_price() / 100 * coupon.discount  # عدد تقسیم 100 ضربدر درصد
                            new_total_price = cart.all_total_price() - discount
                            context = {'cart': cart, 'coupon': coupon, 'new_total_price': new_total_price}
                            return render(request, 'cart/checkout.html.html', context)
                except:
                    messages.error(request, 'this coupon is not active')
                    context = {'cart': cart, 'coupon': coupon_code, 'form': form}
                    return render(request, 'cart/checkout.html', context)
        return redirect('cart:checkout_cart')


class CheckoutCart(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
      #  form = CouponForm()
        context = {'cart': cart}    # , 'form': form
        return render(request, 'cart/checkout.html', context)


class DetailCart(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'cart/detail-cart.html', {'cart': cart})


class AddCartObject(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product)
        messages.success(request, 'محصول مورد نظر به سبد خرید شما اضافه شد . ')
        return redirect('services:detail_product', product.slug)


class RemoveObject(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product=product)
        return redirect('cart:detail_cart')

cart/templates/cart/checkout.html
{% extends 'base.html' %}
{% block content %}
    <div class="container" style="margin-top: 60px">
        <h2 class="section-heading mb-5">
            <span class="section-heading-lower">Check Out</span>
        </h2>
        <p class="address mb-5">
            <em>
                {% if new_total_price %}
                    <p><h3>ToTal Price : {{ cart.all_total_price }}</h3></p>
                    <p><h3><big>New Price : {{ new_total_price }}</big></h3></p>
                {% else %}
                    <p>Total Price : {{ cart.all_total_price  }}</p>
                    <!--
                    <form action="{% url 'orders:apply_coupon'%}" method="post">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit">Apply Coupon</button>
                    </form>
                    --!>

                {% endif %}
        <a class="btn bg-dark" href="{% url 'orders:create_order' %}" type="submit">خرید</a>
            </em>
        </p>
    </div>
{% endblock content %}

cart/templates/cart/detail-cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container align-content-centerer">
<table class="table table-dark col-12" style="margin-top: 60px;">
  <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">محصول</th>
        <th scope="col">قیمت</th>
        <th scope="col">حذف</th>
     </tr>
     </thead>
     <tbody>
     {% for item in cart %}
         <tr>
             <th scope="row">{{ forloop.counter }}</th>
             <td>{{ item.product }}</td>
             <td>{% if item.product.discount_code > 0 %}
                     <p>{{ item.product.price_whit_discount }}</p>
                 {% else %}
                    {{ item.price }}</td>
                {% endif %}
             <td><a href="{% url 'cart:remove_object' item.product.id %}">حذف از سبد</a></td>
         </tr>
     {% endfor %}
     <tr>
         <td>قیمت کل</td>
         <td colspan="1"></td>
         {% if cart.all_total_price == 0 %}
             <td class="align-content-center">سبد خرید شما خالی است</td>
         {% else %}
            <td class="align-content-center">{{ cart.all_total_price }}</td>
         {% endif %}
     </tr>
     </tbody>
 </table>
        {% if cart.all_total_price != 0 %}
            <center><a href="{% url 'cart:checkout_cart'  %}" class="btn btn-primary">Checkout</a></center>
        {% endif %}
     <br>
    </div>
{% endblock %}