CnNazaninProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('services/', include('services.urls', namespace='services')),
    path('other/', include('other.urls', namespace='other')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),
    path('register/', views.UserRegister.as_view(), name='register'),
    path('profile/<int:user_id>/', views.UserProfile.as_view(), name='profile'),
    path('update_profile/<int:user_id>/', views.UpdateProfile.as_view(), name='update_profile'),
    # ---------------------------------------- Reset password -------------------------------------- #
    path('reset/', views.ResetPassword.as_view(), name='reset'),
    path('reset/done/', views.DonePassword.as_view(), name='reset_done'),
    path('confirm/<uidb64>/<token>/', views.ConfirmPassword.as_view(), name='confirm_password'),
    path('confirm/done/', views.Complete.as_view(), name='confirm_done'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail_cart/', views.DetailCart.as_view(), name='detail_cart'),
    path('add_object/<int:product_id>/', views.AddCartObject.as_view(), name='add_object'),
    path('remove_object/<int:product_id>/', views.RemoveObject.as_view(), name='remove_object'),
#    path('apply_coupon/', views.ApplyCoupon.as_view(), name='apply_coupon'),
    path('checkout_cart/', views.CheckoutCart.as_view(), name='checkout_cart'),

]

core/urls.py
from django.urls import path
from . import views


app_name = 'core'


urlpatterns = [
    path('', views.Home.as_view(), name='home'),

]

other/urls.py
from . import views
from django.urls import path


app_name = 'other'

urlpatterns = [

    # --------------------------------------- contact us --------------------------------------------- #
    path('contact_us/', views.ContactUs.as_view(), name='contact_us'),

    # ------------------------------------ news ------------------------------------------------------- #
    path('sort_news_by_date/', views.SortNewsByDate.as_view(), name='sort_news_by_date'),
    path('sort_news_by_must_visited/', views.SortNewsByMustVisit.as_view(), name='sort_news_by_must_visited'),
    path('search_news/', views.SearchNews.as_view(), name='search_news'),
    path('add_reply_news/<int:news_id>/<int:comment_id>/', views.add_reply_news, name='add_reply_news'),
    path('news/', views.AllNews.as_view(), name='all_news'),
    path('detail_news/<slug:slug>/', views.DetailNews.as_view(), name='detail_news'),
    # ------------------------------------ product filter ---------------------------------------------- #
    path('search/', views.SearchProduct.as_view(), name='search'),
    path('search_result/', views.SearchResult.as_view(), name='search_result'),
    path('sort_by_lowest_price/', views.SortByLowestPrice.as_view(), name='sort_by_lowest_price'),
    path('sort_by_date/', views.SortByDate.as_view(), name='sort_by_date'),
    path('free_products/', views.FreeProduct.as_view(), name='free-products'),
    path('sort_by_must_visited/', views.SortProductByMustVisit.as_view(), name='sort_by_must_visited'),

]

services/urls.py
from . import views
from django.urls import path


app_name = 'services'

urlpatterns = [
    path('add_reply/<int:product_id>/<int:comment_id>/', views.add_reply_product, name='add_reply'),
    # ---------------------------------- services ----------------------------------- #
    path('web_design/', views.WebDesign.as_view(), name='web_design'),
    path('graphic_design/', views.GraphicDesign.as_view(), name='graphic_design'),
    path('research_and_type/', views.ResearchAndTyping.as_view(), name='research_and_type'),
    path('online_registration/', views.OnlineRegistration.as_view(), name='online_registration'),
    path('translation/', views.Translation.as_view(), name='translation'),


    # __________________________________ product  ____________________________________ #
    path('products/', views.AllProduct.as_view(), name='all_product'),
    path('products/<slug:slug>/', views.AllProduct.as_view(), name='category_filter'),
    path('detail_product/<slug:slug>/', views.DetailProduct.as_view(), name='detail_product'),

]

templates/base-form.html
<!DOCTYPE html>
{% load static %}
{% load django_bootstrap5 %}
<html lang="en" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block tit %}{% endblock tit %}</title>
    <link rel="stylesheet" href="{% static 'accounts/fonts/material-icon/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
</head>
<body>
{% include 'messages.html' %}
{% block content %}
{% endblock %}
<script src="{% static 'accounts/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'accounts/js/main.js' %}"></script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% load static %}
<html lang="en" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>{% block tit %}{% endblock tit %}</title>

    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="it">
    <meta name="keywords" content="Rapoo,creative, agency, startup,onepage, clean, modern,business, company,it">
    <meta name="author" content="themefisher.com">
    <!-- bootstrap.min css -->
    <link rel="stylesheet" href="{% static 'core/plugins/bootstrap/css/bootstrap.min.css' %}">
    <!-- Animate Css -->
    <link rel="stylesheet" href="{% static 'core/plugins/animate-css/animate.css' %}">
    <!-- Icon Font css -->
    <link rel="stylesheet" href="{% static 'core/plugins/fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'core/plugins/fonts/Pe-icon-7-stroke.css' %}">
    <!-- Themify icon Css -->
    <link rel="stylesheet" href="{% static 'core/plugins/themify/css/themify-icons.css' %}">
    <!-- Slick Carousel CSS -->
    <link rel="stylesheet" href="{% static 'core/plugins/slick-carousel/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'core/plugins/slick-carousel/slick/slick-theme.css' %}">
    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    {% block h %}{% endblock h %}

</head>
<body  id="top-header">
{% include 'messages.html' %}
<div id="page-loader">
    <div class="loader-icon fa fa-spin colored-border"></div>
</div>
    <div class="top-bar bg-dark " id="top-bar">
        <div class="container">
            <div class="row align-items-center">
                    <ul class="d-flex list-unstyled header-socials float-lg-none">
                        <li><a href="http://wa.me/+989931258311"> <i class="fab fa-whatsapp"></i></a></li>
                        <li><a href="https://instagram.com/internet_cafe.nazanin"> <i class="fab fa-instagram"></i></a></li>
                    </ul>
            </div>
        </div>
    </div>

    <div class="logo-bar d-none d-md-block d-lg-block bg-light" dir="ltr">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="logo d-none d-lg-block">
                        <!-- Brand -->
                        <a class="navbar-brand js-scroll-trigger" href="{% url 'core:home' %}">
                            <h2>CnNazanin</h2>
                        </a>
                    </div>
                </div>

                <div class="col-lg-8 justify-content-end ml-lg-auto d-flex col-12 col-md-12 justify-content-md-center">
                    <div class="top-info-block d-inline-flex">
                        <div class="icon-block">
                            <i class="ti-mobile"></i>
                        </div>
                        <div class="info-block">
                            <h5 class="font-weight-500">09931258311</h5>
                            <p><a href='sms:09931258311'> پیام</a>   <a href='tel:09931258311'>تماس</a></p>
                        </div>
                    </div>

                    <div class="top-info-block d-inline-flex">
                        <div class="icon-block">
                            <i class="ti-email"></i>
                        </div>
                        <div class="info-block">
                            <h5 class="font-weight-500">CnNazanin@gamil.com</h5>
                            <a href='mailto:internetcafenazanin@gmail.com'><p>Email Us</p></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- NAVBAR
    ================================================= -->
    <div class="main-navigation" id="mainmenu-area">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary main-nav navbar-togglable rounded-radius">

                <a class="navbar-brand d-lg-none d-block" href="">
                    <h4>CnNazanin</h4>
                </a>
                <!-- Toggler -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span>
                </button>

                <!-- Collapse -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <!-- Links -->
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:home' %}">
                                صفحه اصلی
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarWelcome" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                خدمات ما
                            </a>
                            <div class="dropdown-menu text-center" aria-labelledby="navbarWelcome">
                                 <a class="dropdown-item " href="{% url 'services:web_design' %}">
                                    طراحی سایت
                                </a>
                                <a class="dropdown-item " href="{% url 'services:graphic_design' %}">
                                    طراحی گرافیکی
                                </a>
                                <a class="dropdown-item " href="{% url 'services:online_registration' %}">
                                    ثبت نام اینترنتی
                                </a>
                                <a class="dropdown-item " href="{% url 'services:research_and_type' %}">
                                    تحقیق و تایپ
                                </a>
                                <a class="dropdown-item " href="{% url 'services:translation' %}">
                                    ترجمه
                                </a>

                            </div>
                        </li>

                        {% if request.user.is_authenticated %}
                            <li class="nav-item ">
                                <a href="{% url 'accounts:logout' %}" class="nav-link js-scroll-trigger">
                                    خروج
                                </a>
                            <li class="nav-item ">
                                <a href="{% url 'accounts:profile' request.user.id %}" class="nav-link js-scroll-trigger">
                                    پروفایل
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item ">
                            <a href="{% url 'accounts:login' %}" class="nav-link js-scroll-trigger">
                                ورود
                            </a>
                        </li>
                        {% endif %}
                        <li class="nav-item ">
                            <a href="{% url 'other:contact_us' %}" class="nav-link js-scroll-trigger">
                                ارتباط با ما
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a href="{% url 'services:all_product' %}" class="nav-link">
                                نمونه کارها
                            </a>
                        </li>
                            <li class="nav-item ">
                                <a href="{% url 'cart:detail_cart'  %}" class="nav-link js-scroll-trigger">
                                    سبد خرید
                                </a>
                            </li>
                    </ul>

                    <ul class="ml-lg-auto list-unstyled m-0">
                        <li><a href="{% url 'other:all_news' %}" class="btn btn-white btn-circled"><h5>جدیدترین اخبار</h5></a></li>

                    </ul>

                </div> <!-- / .navbar-collapse -->
            </nav>

        </div> <!-- / .container -->
    </div>


{% block content %}{% endblock content %}
 <footer class="section " id="footer">
        <div class="overlay footer-overlay"></div>
        <!--Content -->
        <div class="container">
            <div class="row justify-content-start">
                <div class="col-lg-3 col-sm-12">
                    <div class="footer-widget">
                        <!-- Brand -->
                        <a href="#" class="footer-brand text-white">
                            CnNazanin
                        </a>
                        <p>Text About WebSite</p>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-6">
                    <div class="footer-widget">
                        <h3> َشبکه های اجتماعی</h3>
                        <!-- Links -->
                        <ul class="list-unstyled footer-links">
                            <li><a href="#"><i class="fab fa-instagram"></i>instagram</a></li>
                            <li>
                            <a href="#"><i class="fab fa-telegram"></i>telegram
                            </a></li>
                            <li><a href="#"><i class="fab fa-whatsapp"></i>whatsapp
                            </a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- / .row -->


            <div class="row text-right pt-2">
                <div class="col-lg-12">
                    <!-- Copyright -->
                    <p class="footer-brand">
                        CnNazanin
                    </p>
                </div>
            </div> <!-- / .row -->
        </div> <!-- / .container -->
    </footer>

    <!--  Page Scroll to Top  -->
    <a class="scroll-to-top js-scroll-trigger" href="#top-header">
        <i class="fa fa-angle-up"></i>
    </a>
    <!--
    Essential Scripts
    =====================================-->
    <!-- Main jQuery -->
    <script src="{% static 'core/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.1 -->
    <script src="{% static 'core/plugins/bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'core/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Slick Slider -->
    <script src="{% static 'coreplugins/slick-carousel/slick/slick.min.js' %}"></script>
    <script src="{% static 'core/js/jquery.easing.1.3.js' %}"></script>
    <!-- Map Js -->
    <script src="{% static 'core/plugins/google-map/gmap3.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDwIQh7LGryQdDDi-A603lR8NqiF3R_ycA"></script>

    <script src="{% static 'core/js/form/contact.js' %}"></script>
    <script src="{% static 'core/js/theme.js' %}"></script>

</body>
</html>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}