CnNazaninProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('services/', include('services.urls', namespace='services')),
    path('other/', include('other.urls', namespace='other')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail_cart/', views.DetailCart.as_view(), name='detail_cart'),
    path('add_object/<int:product_id>/', views.AddCartObject.as_view(), name='add_object'),
    path('remove_object/<int:product_id>/', views.RemoveObject.as_view(), name='remove_object'),
#    path('apply_coupon/', views.ApplyCoupon.as_view(), name='apply_coupon'),
    path('checkout_cart/', views.CheckoutCart.as_view(), name='checkout_cart'),

]

other/urls.py
from . import views
from django.urls import path


app_name = 'other'

urlpatterns = [

    # --------------------------------------- contact us --------------------------------------------- #
    path('contact_us/', views.ContactUs.as_view(), name='contact_us'),

    # ------------------------------------ news ------------------------------------------------------- #
    path('sort_news_by_date/', views.SortNewsByDate.as_view(), name='sort_news_by_date'),
    path('sort_news_by_must_visited/', views.SortNewsByMustVisit.as_view(), name='sort_news_by_must_visited'),
    path('search_news/', views.SearchNews.as_view(), name='search_news'),
    path('add_reply_news/<int:news_id>/<int:comment_id>/', views.add_reply_news, name='add_reply_news'),
    path('news/', views.AllNews.as_view(), name='all_news'),
    path('detail_news/<slug:slug>/', views.DetailNews.as_view(), name='detail_news'),
    # ------------------------------------ product filter ---------------------------------------------- #
    path('search/', views.SearchProduct.as_view(), name='search'),
    path('search_result/', views.SearchResult.as_view(), name='search_result'),
    path('sort_by_lowest_price/', views.SortByLowestPrice.as_view(), name='sort_by_lowest_price'),
    path('sort_by_date/', views.SortByDate.as_view(), name='sort_by_date'),
    path('free_products/', views.FreeProduct.as_view(), name='free-products'),
    path('sort_by_must_visited/', views.SortProductByMustVisit.as_view(), name='sort_by_must_visited'),

]

services/urls.py
from . import views
from django.urls import path


app_name = 'services'

urlpatterns = [
    path('add_reply/<int:product_id>/<int:comment_id>/', views.add_reply_product, name='add_reply'),
    # ---------------------------------- services ----------------------------------- #
    path('web_design/', views.WebDesign.as_view(), name='web_design'),
    path('graphic_design/', views.GraphicDesign.as_view(), name='graphic_design'),
    path('research_and_type/', views.ResearchAndTyping.as_view(), name='research_and_type'),
    path('online_registration/', views.OnlineRegistration.as_view(), name='online_registration'),
    path('translation/', views.Translation.as_view(), name='translation'),


    # __________________________________ product  ____________________________________ #
    path('products/', views.AllProduct.as_view(), name='all_product'),
    path('products/<slug:slug>/', views.AllProduct.as_view(), name='category_filter'),
    path('detail_product/<slug:slug>/', views.DetailProduct.as_view(), name='detail_product'),

]

services/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from taggit.managers import TaggableManager
from django.core.validators import MaxValueValidator, MinValueValidator


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.CharField(max_length=200, unique=True)
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE,
                                     related_name='category_rel_with_self', null=True, blank=True)
    is_sub = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def category_url(self):
        return reverse('services:category_filter', args=[self.slug, ])


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='product')
    title = models.CharField(max_length=300, unique=True, null=True, blank=True)
    slug = models.CharField(max_length=300, unique=True)
    price = models.IntegerField(default=0)
    discount_price = models.IntegerField(default=0)
    pic = models.ImageField(null=True, blank=True, upload_to='example/')
    short_description = models.CharField(null=True, blank=True, max_length=200)
    description = RichTextUploadingField(null=True, blank=True)
    product_file = RichTextUploadingField(null=True, blank=True)
    most_visited = models.SmallIntegerField(null=True, blank=True, default=0)
    pay = models.BooleanField(default=False)
    tags = TaggableManager()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def price_whit_discount(self):
        if self.discount_price > 0:
            self.price = self.discount_price
            return self.price
        return self.price

    def __str__(self):
        return self.slug

    def get_short_description(self):
        return self.short_description[:50]


class ProductComment(models.Model):
    name = models.CharField(max_length=70)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='pcomment')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='rcomment')
    is_reply = models.BooleanField(default=False)
    comment = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} - {self.comment[:30]}'

    class Meta:
        ordering = ('-created',)


class CategoryDescription(models.Model):
    category = models.OneToOneField(Category, on_delete=models.CASCADE, related_name='category_description')
    body = RichTextUploadingField()

    def __str__(self):
        return f'{self.category.name}'

services/forms.py
from django import forms
from .models import ProductComment


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = ProductComment
        fields = ('comment', 'name')


class AddReplyForm(forms.ModelForm):
    class Meta:
        model = ProductComment
        fields = ('comment', 'name')

services/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Category, CategoryDescription, ProductComment
from .forms import AddReplyForm, AddCommentForm
from django.views import View
from django.contrib import messages
from django.db.models import Q
from other.forms import SearchProductForm


def add_reply_product(request, product_id, comment_id):
    product = get_object_or_404(Product, id=product_id)
    comment = get_object_or_404(ProductComment, pk=comment_id)
    if request.method == 'POST':
        form = AddReplyForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            reply = ProductComment.objects.create(name=cd['name'], product=product, reply=comment,
                                                  comment=cd['comment'], is_reply = True)
            reply.save()
            return redirect('services:detail_product', product.slug)
    return redirect('services:detail_product', product.slug)


# -------------------------------------------- product ----------------------------------------------- #


class AllProduct(View):
    def get(self, request, slug=None):
        products = Product.objects.all().order_by('-created')
        categories = Category.objects.filter(is_sub=False)
        if slug:
            category = get_object_or_404(Category, slug=slug)
            products = products.filter(category=category)
        form = SearchProductForm(request.GET)
        if 'search' in request.GET:
            if form.is_valid():
                cd = form.cleaned_data
                products = products.filter(Q(title__icontains=cd['search']) | Q(short_description=cd['search']))
                return render(request, 'other/search-result.html', {'form': form, 'products': products})
            messages.error(request, 'please inter valid data', 'error')
            return render(request, 'services/all-product.html', {'form': form})
        context = {'products': products, 'categories': categories, 'form': form}
        return render(request, 'services/all-product.html', context)


class DetailProduct(View):
    form_class = AddCommentForm

    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        product.most_visited += 1
        product.save()
        comments = ProductComment.objects.filter(product=product, is_reply=False)
        reply_form = AddReplyForm()
        similar_products = product.tags.similar_objects()
        context = {'product': product, 'similar_products': similar_products, 'comments': comments,
                   'form': self.form_class, 'reply': reply_form}
        return render(request, 'services/detail-product.html', context)

    def post(self,  request, slug):
        product = get_object_or_404(Product, slug=slug)
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_comment = ProductComment.objects.create(comment=cd['comment'], product=product, name=cd['name'])
            new_comment.save()
            messages.success(request, 'نظر شما با موفقیت اضافه شد')
            return redirect('services:detail_product', product.slug)
        messages.success(request, 'لطفادوباره امتحان کنید')
        return redirect('services:detail_product', product.slug)


# --------------------------------------------- خدمات -------------------------------------


class WebDesign(View):
    def get(self, request):
        products = Product.objects.filter(category__name='طراحی سایت')[:5]
        description = CategoryDescription.objects.get(category__name='طراحی سایت')
        context = {'products': products, 'description': description}
        return render(request, 'services/services.html', context)


class GraphicDesign(View):
    def get(self, request):
        products = Product.objects.filter(category__name='طراحی گرافیکی')[:5]
        description = CategoryDescription.objects.get(category__name='طراحی گرافیکی')
        context = {'products': products, 'description': description}
        return render(request, 'services/services.html', context)


class Translation(View):
    def get(self, request):
        products = Product.objects.filter(category__name='ترجمه')[:5]
        description = CategoryDescription.objects.get(category__name='ترجمه')
        context = {'products': products, 'description': description}
        return render(request, 'services/services.html', context)


class OnlineRegistration(View):
    def get(self, request):
        products = Product.objects.filter(category__name='ثبت نام اینترنتی')[:5]
        description = CategoryDescription.objects.get(category__name='ثبت نام اینترنتی')
        context = {'products': products, 'description': description}
        return render(request, 'services/services.html', context)


class ResearchAndTyping(View):
    def get(self, request):
        products = Product.objects.filter(category__name='تحقیق و تایپ')[:5]
        description = CategoryDescription.objects.get(category__name='تحقیق و تایپ')
        context = {'products': products, 'description': description}
        return render(request, 'services/services.html', context)

services/templates/services/all-product.html
{% extends 'base.html' %}
{% block tit %}محصولات{% endblock tit %}
{% block content %}


    <div class="navbar navbar-dark row" style="margin-top: 35px; margin-right: 3%">
        <form action="">
            {{ form }}
            <input type="submit" value="جستوجو">
        </form>
    </div>

    <div class="row" style="margin-left: 5%; margin-right: 5%">
        <div id="filter pro" class="col-lg-6 col-md-6 col-sm-6 col-xl-6">
            <div  class="dropdown-toggle btn btn-block btn-dark "
                  style="margin-top: 1%;" id="filter" role="button" data-toggle="dropdown">
               فیلتر کردن محصولات</div>
                <div class="dropdown-menu text-right" aria-labelledby="filter">
                    <a href="{% url 'services:all_product' %}" class="dropdown-item">همه محصولات</a>
                    <a href="{% url 'other:sort_by_must_visited' %}" class="dropdown-item">پربازدید ترین ها</a>
                    <a href="{% url 'other:free-products' %}" class="dropdown-item">محصولات رایگان</a>
                    <a href="{% url 'other:sort_by_date' %}" class="dropdown-item">جدیدترین ها </a>
                    <a href="{% url 'other:sort_by_lowest_price' %}" class="dropdown-item">ارزانترین ها</a>

                </div>
        </div>

        <div id="category" class="col-lg-6 col-md-6 col-sm-6 col-xl-6">
            <div  class=" dropdown-toggle btn btn-block btn-dark"  style="margin-top: 1%;" href="{% url 'services:all_product' %}" id="navbarWelcome" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               دسته بندی</div>
                <div class="dropdown-menu text-center"  aria-labelledby="navbarWelcome">
                    <a href="{% url 'services:all_product' %}" class="dropdown-item">همه محصولات</a>
                    {% for category in categories %}
                        <a href="{{ category.category_url }}">{{ category.name }}</a>
                         {% for sub in category.category_rel_with_self.all %}
                        <a href="{{ sub.category_url }}" class="dropdown-item">{{ sub.name }}</a>
                        {% endfor %}
                    {% endfor %}
                </div>
         </div>
    </div>



    <div class="row" style="margin-top: 60px; margin-right: 2px; margin-left: 2px;">
        {% for product in products %}
            <div class="col-sm-12 col-lg-2 col-md-2 col-xl-2" style="margin: 2px">
                <div class="thumbnail">
                    <img src="{{ product.pic.url }}" alt="{{ product.title }}" height="150" width="100%">
                    <div class="caption">
                        <h3>{{ product.title }}</h3>
                        <p>{% if product.short_description %}
                            {{ product.get_short_description }}
                            {% endif %}

                        </p>
                        <p> <a href="{% url 'services:detail_product' product.slug %}" class="btn btn-primary btn-block" role="button">دیدن جزییات</a></p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

services/templates/services/detail-product.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block tit %}detail{% endblock tit %}
{% block content %}
    <div class="container text-center" style="margin-top: 60px;">

        <h3 class="">{{ product.title }}</h3>
        {{ product.description | safe }}
        {% if product.price != 0 %}
            {% if product.pay == False %}
            <big> {{ product.price }}تومان </big>
                {% if product.discount_price > 0 %}
                     <p>قیمت با تخفیف ویژه {{ product.price_whit_discount }} تومان </p>
                {% endif %}
            <form action="{% url 'cart:add_object' product.id %}" method="post">
            {% csrf_token %}
            <input type="submit" name="pay" class="btn btn-success " value="افزودن به سبد خرید">
            </form>
            {% else %}
                {{ product.product_file|safe }}
            {% endif %}
        {% endif %}


        <div class="row" style="margin-top: 50px; margin-right: 2%; margin-left: 12%;">
            {% for similar in similar_products  %}
                {% if similar.title != product.title %}
                    <div class="col-3" style="margin-right: 2%">
                        <div class="thumbnail">
                            <img src="{{ similar.pic.url }}" alt="{{ similar.title }}" height="150" width="100%">
                            <div class="caption">
                                <h3>{{ similar.title }}</h3>
                                <p>
                                    {% if short_description %}
                                        {{ similar.get_short_description }}
                                    {% endif %}
                                </p>
                                <p><a href="{% url 'services:detail_product' similar.slug %}" class="btn btn-primary btn-block" role="button">دیدن جزییات</a></p>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% empty %}
                محصول مشابه این محصول وجود ندارد.
            {% endfor %}
        </div>
    <hr>
    	<form action="" method="post" class="col-6">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send" class="btn btn-primary">
        </form>
        {% for comment in comments %}
        <div>
            <p class="card-header">{{ comment.name }}</p>
            <p class="card-body">{{ comment.comment }}
                <div class="card-body">
                    <form action="{% url 'services:add_reply' product.id comment.id %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Send">
                    </form>
                </div>

                {% for reply in comment.rcomment.all %}
                    <p class="bg-primary text-white p-3 m-5">{{ reply.name }} <br/> {{ reply.comment }}</p>
                {% endfor %}
            </p>
        </div>
    {% empty %}
        <p>نظری وجود ندارد</p>
    {% endfor %}



    </div>


{% endblock content %}

services/templates/services/services.html
{% extends 'base.html' %}
{% block content %}

    <div style="margin-top: 60px; ; margin-right: 20px; margin-left: 20px;">

        {{ description.body|safe }}
    </div>

    <div class="row" style="margin-top: 10px; margin-right: 2px; margin-left: 2px;">

        {% for product in products %}
            <div class="col-sm-12 col-lg-2 col-md-2 col-xl-2" style="margin: 2px">
                <div class="thumbnail">
                    <img src="{{ product.pic.url }}" alt="{{ product.title }}" height="150" width="100%">
                    <div class="caption">
                        <h3>{{ product.title }}</h3>
                        <p>{% if product.short_description %}
                            {{ product.get_short_description }}
                            {% endif %}
                        </p>
                        <p> <a href="{% url 'services:detail_product' product.slug %}" class="btn btn-primary btn-block" role="button">دیدن جزییات</a></p>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="text-center col-12">
                <p>محصولی وجود ندارد.</p>
            </div>
        {% endfor %}
    </div>
{% endblock content %}